// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaidOps.Infrastructure.Persistence.Implementations;

#nullable disable

namespace RaidOps.Infrastructure.Persistence.Implementations.Migrations
{
    [DbContext(typeof(RaidOpsDbContext))]
    [Migration("20260520144534_Add-UserGuilds")]
    partial class AddUserGuilds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaidOps.Domain.Models.User", b =>
                {
                    b.Property<string>("DiscordId")
                        .HasColumnType("text");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastRefresh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DiscordId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.UserGuild", b =>
                {
                    b.Property<string>("UserDiscordId")
                        .HasColumnType("text");

                    b.Property<string>("GuildId")
                        .HasColumnType("text");

                    b.Property<string>("GuildIconHash")
                        .HasColumnType("text");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("UserDiscordId", "GuildId");

                    b.ToTable("UserGuilds");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.UserGuild", b =>
                {
                    b.HasOne("RaidOps.Domain.Models.User", "User")
                        .WithMany("UserGuilds")
                        .HasForeignKey("UserDiscordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.User", b =>
                {
                    b.Navigation("UserGuilds");
                });
#pragma warning restore 612, 618
        }
    }
}
