// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaidOps.Infrastructure.Persistence.Implementations;

#nullable disable

namespace RaidOps.Infrastructure.Persistence.Implementations.Migrations
{
    [DbContext(typeof(RaidOpsDbContext))]
    [Migration("20260602141216_AddMediaAndGuildAndSpecsToCharacters")]
    partial class AddMediaAndGuildAndSpecsToCharacters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaidOps.Domain.Models.Character.BattleNetAccount", b =>
                {
                    b.Property<string>("UserDiscordId")
                        .HasColumnType("text");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BattleTag")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BnetId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTimeOffset>("TokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserDiscordId");

                    b.ToTable("BattleNetAccounts");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("BnetCharacterId")
                        .HasColumnType("bigint");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("Faction")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActiveInRaidOps")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("RealmId")
                        .HasColumnType("integer");

                    b.Property<string>("UserDiscordId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ClassId");

                    b.HasIndex("RaceId");

                    b.HasIndex("RealmId");

                    b.HasIndex("UserDiscordId");

                    b.HasIndex("BnetCharacterId", "RealmId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.CharacterExpansionState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<int>("ExpansionId")
                        .HasColumnType("integer");

                    b.Property<string>("GuildName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ItemLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpansionId");

                    b.HasIndex("CharacterId", "ExpansionId")
                        .IsUnique();

                    b.ToTable("CharacterExpansionStates");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.CharacterSpec", b =>
                {
                    b.Property<int>("CharacterExpansionStateId")
                        .HasColumnType("integer");

                    b.Property<int>("SpecId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.HasKey("CharacterExpansionStateId", "SpecId");

                    b.HasIndex("SpecId");

                    b.ToTable("CharacterSpecs");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.Realm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Slug", "Region", "BranchId")
                        .IsUnique();

                    b.ToTable("Realms");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Discord.Guild", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("IconHash")
                        .HasColumnType("text");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Discord.User", b =>
                {
                    b.Property<string>("DiscordId")
                        .HasColumnType("text");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastRefresh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DiscordId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Discord.UserGuild", b =>
                {
                    b.Property<string>("UserDiscordId")
                        .HasColumnType("text");

                    b.Property<string>("GuildId")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("UserDiscordId", "GuildId");

                    b.HasIndex("GuildId");

                    b.ToTable("UserGuilds");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Reference.Branch", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("BnetNamespacePrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("CurrentExpansionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentExpansionId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BnetNamespacePrefix = "dynamic",
                            CurrentExpansionId = 11,
                            Name = "Retail"
                        },
                        new
                        {
                            Id = 2,
                            BnetNamespacePrefix = "dynamic-classic1x",
                            CurrentExpansionId = 1,
                            Name = "Classic Era"
                        },
                        new
                        {
                            Id = 3,
                            BnetNamespacePrefix = "dynamic-classic",
                            CurrentExpansionId = 5,
                            Name = "Classic"
                        },
                        new
                        {
                            Id = 4,
                            BnetNamespacePrefix = "dynamic-classicann",
                            CurrentExpansionId = 2,
                            Name = "Classic Anniversary"
                        });
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Reference.Expansion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ReleaseOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("Expansions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Classic",
                            ReleaseOrder = 1,
                            ShortCode = "Classic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "The Burning Crusade",
                            ReleaseOrder = 2,
                            ShortCode = "TBC"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wrath of the Lich King",
                            ReleaseOrder = 3,
                            ShortCode = "WotLK"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cataclysm",
                            ReleaseOrder = 4,
                            ShortCode = "Cata"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mists of Pandaria",
                            ReleaseOrder = 5,
                            ShortCode = "MoP"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Warlords of Draenor",
                            ReleaseOrder = 6,
                            ShortCode = "WoD"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Legion",
                            ReleaseOrder = 7,
                            ShortCode = "Legion"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Battle for Azeroth",
                            ReleaseOrder = 8,
                            ShortCode = "BfA"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Shadowlands",
                            ReleaseOrder = 9,
                            ShortCode = "SL"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dragonflight",
                            ReleaseOrder = 10,
                            ShortCode = "DF"
                        },
                        new
                        {
                            Id = 11,
                            Name = "The War Within",
                            ReleaseOrder = 11,
                            ShortCode = "TWW"
                        });
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Reference.Race", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Faction")
                        .HasColumnType("integer");

                    b.Property<int>("FirstExpansionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Faction = 1,
                            FirstExpansionId = 1,
                            Name = "Human"
                        },
                        new
                        {
                            Id = 2,
                            Faction = 2,
                            FirstExpansionId = 1,
                            Name = "Orc"
                        },
                        new
                        {
                            Id = 3,
                            Faction = 1,
                            FirstExpansionId = 1,
                            Name = "Dwarf"
                        },
                        new
                        {
                            Id = 4,
                            Faction = 1,
                            FirstExpansionId = 1,
                            Name = "Night Elf"
                        },
                        new
                        {
                            Id = 5,
                            Faction = 2,
                            FirstExpansionId = 1,
                            Name = "Undead"
                        },
                        new
                        {
                            Id = 6,
                            Faction = 2,
                            FirstExpansionId = 1,
                            Name = "Tauren"
                        },
                        new
                        {
                            Id = 7,
                            Faction = 1,
                            FirstExpansionId = 1,
                            Name = "Gnome"
                        },
                        new
                        {
                            Id = 8,
                            Faction = 2,
                            FirstExpansionId = 1,
                            Name = "Troll"
                        },
                        new
                        {
                            Id = 10,
                            Faction = 2,
                            FirstExpansionId = 2,
                            Name = "Blood Elf"
                        },
                        new
                        {
                            Id = 11,
                            Faction = 1,
                            FirstExpansionId = 2,
                            Name = "Draenei"
                        },
                        new
                        {
                            Id = 9,
                            Faction = 2,
                            FirstExpansionId = 4,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 22,
                            Faction = 1,
                            FirstExpansionId = 4,
                            Name = "Worgen"
                        },
                        new
                        {
                            Id = 24,
                            Faction = 3,
                            FirstExpansionId = 5,
                            Name = "Pandaren"
                        },
                        new
                        {
                            Id = 25,
                            Faction = 1,
                            FirstExpansionId = 5,
                            Name = "Pandaren"
                        },
                        new
                        {
                            Id = 26,
                            Faction = 2,
                            FirstExpansionId = 5,
                            Name = "Pandaren"
                        },
                        new
                        {
                            Id = 27,
                            Faction = 2,
                            FirstExpansionId = 8,
                            Name = "Nightborne"
                        },
                        new
                        {
                            Id = 28,
                            Faction = 2,
                            FirstExpansionId = 8,
                            Name = "Highmountain Tauren"
                        },
                        new
                        {
                            Id = 29,
                            Faction = 1,
                            FirstExpansionId = 8,
                            Name = "Void Elf"
                        },
                        new
                        {
                            Id = 30,
                            Faction = 1,
                            FirstExpansionId = 8,
                            Name = "Lightforged Draenei"
                        },
                        new
                        {
                            Id = 31,
                            Faction = 2,
                            FirstExpansionId = 8,
                            Name = "Zandalari Troll"
                        },
                        new
                        {
                            Id = 32,
                            Faction = 2,
                            FirstExpansionId = 8,
                            Name = "Mag'har Orc"
                        },
                        new
                        {
                            Id = 34,
                            Faction = 1,
                            FirstExpansionId = 8,
                            Name = "Dark Iron Dwarf"
                        },
                        new
                        {
                            Id = 35,
                            Faction = 2,
                            FirstExpansionId = 8,
                            Name = "Vulpera"
                        },
                        new
                        {
                            Id = 36,
                            Faction = 1,
                            FirstExpansionId = 8,
                            Name = "Kul Tiran"
                        },
                        new
                        {
                            Id = 37,
                            Faction = 1,
                            FirstExpansionId = 8,
                            Name = "Mechagnome"
                        },
                        new
                        {
                            Id = 52,
                            Faction = 1,
                            FirstExpansionId = 10,
                            Name = "Dracthyr (Alliance)"
                        },
                        new
                        {
                            Id = 70,
                            Faction = 2,
                            FirstExpansionId = 10,
                            Name = "Dracthyr (Horde)"
                        },
                        new
                        {
                            Id = 84,
                            Faction = 1,
                            FirstExpansionId = 11,
                            Name = "Earthen (Alliance)"
                        },
                        new
                        {
                            Id = 85,
                            Faction = 2,
                            FirstExpansionId = 11,
                            Name = "Earthen (Horde)"
                        });
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Reference.Spec", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("FirstExpansionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Specs");

                    b.HasData(
                        new
                        {
                            Id = 71,
                            ClassId = 1,
                            FirstExpansionId = 1,
                            Name = "Arms",
                            Role = 3
                        },
                        new
                        {
                            Id = 72,
                            ClassId = 1,
                            FirstExpansionId = 1,
                            Name = "Fury",
                            Role = 3
                        },
                        new
                        {
                            Id = 73,
                            ClassId = 1,
                            FirstExpansionId = 1,
                            Name = "Protection",
                            Role = 1
                        },
                        new
                        {
                            Id = 65,
                            ClassId = 2,
                            FirstExpansionId = 1,
                            Name = "Holy",
                            Role = 2
                        },
                        new
                        {
                            Id = 66,
                            ClassId = 2,
                            FirstExpansionId = 1,
                            Name = "Protection",
                            Role = 1
                        },
                        new
                        {
                            Id = 70,
                            ClassId = 2,
                            FirstExpansionId = 1,
                            Name = "Retribution",
                            Role = 3
                        },
                        new
                        {
                            Id = 253,
                            ClassId = 3,
                            FirstExpansionId = 1,
                            Name = "Beast Mastery",
                            Role = 3
                        },
                        new
                        {
                            Id = 254,
                            ClassId = 3,
                            FirstExpansionId = 1,
                            Name = "Marksmanship",
                            Role = 3
                        },
                        new
                        {
                            Id = 255,
                            ClassId = 3,
                            FirstExpansionId = 1,
                            Name = "Survival",
                            Role = 3
                        },
                        new
                        {
                            Id = 259,
                            ClassId = 4,
                            FirstExpansionId = 1,
                            Name = "Assassination",
                            Role = 3
                        },
                        new
                        {
                            Id = 260,
                            ClassId = 4,
                            FirstExpansionId = 1,
                            Name = "Outlaw",
                            Role = 3
                        },
                        new
                        {
                            Id = 261,
                            ClassId = 4,
                            FirstExpansionId = 1,
                            Name = "Subtlety",
                            Role = 3
                        },
                        new
                        {
                            Id = 256,
                            ClassId = 5,
                            FirstExpansionId = 1,
                            Name = "Discipline",
                            Role = 2
                        },
                        new
                        {
                            Id = 257,
                            ClassId = 5,
                            FirstExpansionId = 1,
                            Name = "Holy",
                            Role = 2
                        },
                        new
                        {
                            Id = 258,
                            ClassId = 5,
                            FirstExpansionId = 1,
                            Name = "Shadow",
                            Role = 3
                        },
                        new
                        {
                            Id = 250,
                            ClassId = 6,
                            FirstExpansionId = 3,
                            Name = "Blood",
                            Role = 1
                        },
                        new
                        {
                            Id = 251,
                            ClassId = 6,
                            FirstExpansionId = 3,
                            Name = "Frost",
                            Role = 3
                        },
                        new
                        {
                            Id = 252,
                            ClassId = 6,
                            FirstExpansionId = 3,
                            Name = "Unholy",
                            Role = 3
                        },
                        new
                        {
                            Id = 262,
                            ClassId = 7,
                            FirstExpansionId = 1,
                            Name = "Elemental",
                            Role = 3
                        },
                        new
                        {
                            Id = 263,
                            ClassId = 7,
                            FirstExpansionId = 1,
                            Name = "Enhancement",
                            Role = 3
                        },
                        new
                        {
                            Id = 264,
                            ClassId = 7,
                            FirstExpansionId = 1,
                            Name = "Restoration",
                            Role = 2
                        },
                        new
                        {
                            Id = 62,
                            ClassId = 8,
                            FirstExpansionId = 1,
                            Name = "Arcane",
                            Role = 3
                        },
                        new
                        {
                            Id = 63,
                            ClassId = 8,
                            FirstExpansionId = 1,
                            Name = "Fire",
                            Role = 3
                        },
                        new
                        {
                            Id = 64,
                            ClassId = 8,
                            FirstExpansionId = 1,
                            Name = "Frost",
                            Role = 3
                        },
                        new
                        {
                            Id = 265,
                            ClassId = 9,
                            FirstExpansionId = 1,
                            Name = "Affliction",
                            Role = 3
                        },
                        new
                        {
                            Id = 266,
                            ClassId = 9,
                            FirstExpansionId = 1,
                            Name = "Demonology",
                            Role = 3
                        },
                        new
                        {
                            Id = 267,
                            ClassId = 9,
                            FirstExpansionId = 1,
                            Name = "Destruction",
                            Role = 3
                        },
                        new
                        {
                            Id = 268,
                            ClassId = 10,
                            FirstExpansionId = 5,
                            Name = "Brewmaster",
                            Role = 1
                        },
                        new
                        {
                            Id = 269,
                            ClassId = 10,
                            FirstExpansionId = 5,
                            Name = "Windwalker",
                            Role = 3
                        },
                        new
                        {
                            Id = 270,
                            ClassId = 10,
                            FirstExpansionId = 5,
                            Name = "Mistweaver",
                            Role = 2
                        },
                        new
                        {
                            Id = 102,
                            ClassId = 11,
                            FirstExpansionId = 1,
                            Name = "Balance",
                            Role = 3
                        },
                        new
                        {
                            Id = 103,
                            ClassId = 11,
                            FirstExpansionId = 1,
                            Name = "Feral",
                            Role = 3
                        },
                        new
                        {
                            Id = 104,
                            ClassId = 11,
                            FirstExpansionId = 5,
                            Name = "Guardian",
                            Role = 1
                        },
                        new
                        {
                            Id = 105,
                            ClassId = 11,
                            FirstExpansionId = 1,
                            Name = "Restoration",
                            Role = 2
                        },
                        new
                        {
                            Id = 577,
                            ClassId = 12,
                            FirstExpansionId = 7,
                            Name = "Havoc",
                            Role = 3
                        },
                        new
                        {
                            Id = 581,
                            ClassId = 12,
                            FirstExpansionId = 7,
                            Name = "Vengeance",
                            Role = 1
                        },
                        new
                        {
                            Id = 1467,
                            ClassId = 13,
                            FirstExpansionId = 10,
                            Name = "Devastation",
                            Role = 3
                        },
                        new
                        {
                            Id = 1468,
                            ClassId = 13,
                            FirstExpansionId = 10,
                            Name = "Preservation",
                            Role = 2
                        },
                        new
                        {
                            Id = 1473,
                            ClassId = 13,
                            FirstExpansionId = 10,
                            Name = "Augmentation",
                            Role = 3
                        });
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Reference.WowClass", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("FirstExpansionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("WowClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "C79C6E",
                            FirstExpansionId = 1,
                            Name = "Warrior"
                        },
                        new
                        {
                            Id = 2,
                            Color = "F58CBA",
                            FirstExpansionId = 1,
                            Name = "Paladin"
                        },
                        new
                        {
                            Id = 3,
                            Color = "ABD473",
                            FirstExpansionId = 1,
                            Name = "Hunter"
                        },
                        new
                        {
                            Id = 4,
                            Color = "FFF569",
                            FirstExpansionId = 1,
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 5,
                            Color = "FFFFFF",
                            FirstExpansionId = 1,
                            Name = "Priest"
                        },
                        new
                        {
                            Id = 6,
                            Color = "C41F3B",
                            FirstExpansionId = 3,
                            Name = "Death Knight"
                        },
                        new
                        {
                            Id = 7,
                            Color = "0070DE",
                            FirstExpansionId = 1,
                            Name = "Shaman"
                        },
                        new
                        {
                            Id = 8,
                            Color = "69CCF0",
                            FirstExpansionId = 1,
                            Name = "Mage"
                        },
                        new
                        {
                            Id = 9,
                            Color = "9482C9",
                            FirstExpansionId = 1,
                            Name = "Warlock"
                        },
                        new
                        {
                            Id = 10,
                            Color = "00FF96",
                            FirstExpansionId = 5,
                            Name = "Monk"
                        },
                        new
                        {
                            Id = 11,
                            Color = "FF7D0A",
                            FirstExpansionId = 1,
                            Name = "Druid"
                        },
                        new
                        {
                            Id = 12,
                            Color = "A330C9",
                            FirstExpansionId = 7,
                            Name = "Demon Hunter"
                        },
                        new
                        {
                            Id = 13,
                            Color = "33937F",
                            FirstExpansionId = 10,
                            Name = "Evoker"
                        });
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.BattleNetAccount", b =>
                {
                    b.HasOne("RaidOps.Domain.Models.Discord.User", "User")
                        .WithOne()
                        .HasForeignKey("RaidOps.Domain.Models.Character.BattleNetAccount", "UserDiscordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.Character", b =>
                {
                    b.HasOne("RaidOps.Domain.Models.Reference.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidOps.Domain.Models.Reference.WowClass", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidOps.Domain.Models.Reference.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidOps.Domain.Models.Character.Realm", "Realm")
                        .WithMany("Characters")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidOps.Domain.Models.Discord.User", "User")
                        .WithMany()
                        .HasForeignKey("UserDiscordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Class");

                    b.Navigation("Race");

                    b.Navigation("Realm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.CharacterExpansionState", b =>
                {
                    b.HasOne("RaidOps.Domain.Models.Character.Character", "Character")
                        .WithMany("ExpansionStates")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidOps.Domain.Models.Reference.Expansion", "Expansion")
                        .WithMany()
                        .HasForeignKey("ExpansionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Expansion");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.CharacterSpec", b =>
                {
                    b.HasOne("RaidOps.Domain.Models.Character.CharacterExpansionState", "CharacterExpansionState")
                        .WithMany("Specs")
                        .HasForeignKey("CharacterExpansionStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidOps.Domain.Models.Reference.Spec", "Spec")
                        .WithMany()
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterExpansionState");

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.Realm", b =>
                {
                    b.HasOne("RaidOps.Domain.Models.Reference.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Discord.UserGuild", b =>
                {
                    b.HasOne("RaidOps.Domain.Models.Discord.Guild", "Guild")
                        .WithMany("UserGuilds")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidOps.Domain.Models.Discord.User", "User")
                        .WithMany("UserGuilds")
                        .HasForeignKey("UserDiscordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Reference.Branch", b =>
                {
                    b.HasOne("RaidOps.Domain.Models.Reference.Expansion", "CurrentExpansion")
                        .WithMany()
                        .HasForeignKey("CurrentExpansionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentExpansion");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Reference.Spec", b =>
                {
                    b.HasOne("RaidOps.Domain.Models.Reference.WowClass", "Class")
                        .WithMany("Specs")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.Character", b =>
                {
                    b.Navigation("ExpansionStates");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.CharacterExpansionState", b =>
                {
                    b.Navigation("Specs");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Character.Realm", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Discord.Guild", b =>
                {
                    b.Navigation("UserGuilds");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Discord.User", b =>
                {
                    b.Navigation("UserGuilds");
                });

            modelBuilder.Entity("RaidOps.Domain.Models.Reference.WowClass", b =>
                {
                    b.Navigation("Specs");
                });
#pragma warning restore 612, 618
        }
    }
}
