<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Authentication\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RaidOps.Domain\RaidOps.Domain.csproj" />
    <ProjectReference Include="..\RaidOps.ExternalApplication.Contracts\RaidOps.ExternalApplication.Contracts.csproj" />
  </ItemGroup>

</Project>
