using System.Security.Claims;

namespace RaidOps.Application.Contracts.Services;

/// <summary>
/// Provides operations for generating and validating JWT access and refresh tokens.
/// </summary>
public interface IJwtService
{
    /// <summary>
    /// Generates a short-lived JWT access token for the specified user.
    /// </summary>
    /// <param name="discordId">The user's Discord snowflake ID, stored as the <c>sub</c> claim.</param>
    /// <param name="username">The user's Discord username, stored as the <c>name</c> claim.</param>
    /// <returns>
    /// A tuple containing the signed JWT string and its UTC expiration timestamp.
    /// </returns>
    (string token, DateTime expiry) GenerateAccessToken(string discordId, string username);

    /// <summary>
    /// Generates a long-lived JWT refresh token for the specified user.
    /// </summary>
    /// <param name="discordId">The user's Discord snowflake ID, stored as the <c>sub</c> claim.</param>
    /// <returns>
    /// A tuple containing the signed JWT string and its UTC expiration timestamp.
    /// </returns>
    (string token, DateTime expiry) GenerateRefreshToken(string discordId);

    /// <summary>
    /// Validates a refresh token and returns the associated claims principal if the token is valid.
    /// </summary>
    /// <param name="token">The JWT refresh token string to validate.</param>
    /// <returns>
    /// The <see cref="ClaimsPrincipal"/> extracted from the token, or <c>null</c> if the token
    /// is expired, tampered with, or otherwise invalid.
    /// </returns>
    ClaimsPrincipal? ValidateRefreshToken(string token);

    /// <summary>
    /// Generates a short-lived CSRF state token for the Discord bot OAuth2 flow.
    /// The token embeds the target guild ID and the initiating user's Discord ID,
    /// and expires after 10 minutes.
    /// </summary>
    /// <param name="guildId">The Discord snowflake ID of the guild being registered.</param>
    /// <param name="discordId">The Discord snowflake ID of the user initiating the registration.</param>
    /// <param name="returnTo">
    /// Optional discriminator identifying where the front end should land after the round-trip
    /// completes (e.g. <c>"get-started"</c>). Carried through as-is — callers validate it against
    /// an allow-list before acting on it.
    /// </param>
    /// <returns>A signed JWT string to be passed as the OAuth2 <c>state</c> parameter.</returns>
    string GenerateStateToken(string guildId, string discordId, string? returnTo = null);

    /// <summary>
    /// Validates a state token generated by <see cref="GenerateStateToken"/> and extracts its claims.
    /// </summary>
    /// <param name="token">The JWT state token to validate.</param>
    /// <returns>
    /// A tuple of <c>(GuildId, DiscordId, ReturnTo)</c> if the token is valid and not expired;
    /// <c>null</c> otherwise. <c>ReturnTo</c> is <c>null</c> when the token was generated without one.
    /// </returns>
    (string GuildId, string DiscordId, string? ReturnTo)? ValidateStateToken(string token);

    /// <summary>
    /// Generates a short-lived CSRF state token for the Battle.net OAuth2 link flow.
    /// Embeds the user's Discord ID and their BNet region, expiring after 10 minutes.
    /// </summary>
    /// <param name="discordId">The Discord snowflake ID of the user linking their BNet account.</param>
    /// <param name="region">BNet region code ("us", "eu", "kr", "tw") chosen by the user.</param>
    /// <returns>A signed JWT string to be passed as the OAuth2 <c>state</c> parameter.</returns>
    string GenerateBnetStateToken(string discordId, string region);

    /// <summary>
    /// Validates a BNet state token generated by <see cref="GenerateBnetStateToken"/> and extracts its claims.
    /// </summary>
    /// <param name="token">The JWT state token to validate.</param>
    /// <returns>
    /// A tuple of <c>(DiscordId, Region)</c> if the token is valid and not expired; <c>null</c> otherwise.
    /// </returns>
    (string DiscordId, string Region)? ValidateBnetStateToken(string token);
}
